### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by tim-rohrer** [Zverik/regional#3]
I built an OSM tile server and was in the process of incorporating updates when I ran into two issues (so far). With the [help of others](https://help.openstreetmap.org/questions/63902/what-is-causing-this-error-when-i-try-to-update-osm-data) we tentatively resolved two issues.

The first resolution involved changing the `argparse.FileType` to `rb` vice `r`. It is totally unclear to me what changed, I assume with the data input file.

The second issue involved python3 vs python2. There was a use of `long` that I had to change to `int`.

While tempted to do a PR, I simply don't know the code or system well enough to be confident these are the *right* fixes? And, I'm still running the update at this time.

**Comment by Zverik** [comment]
Your findings may be correct. Lxml probably expects a binary stream. As for `long`, I was unsure `int` would accomodate 64bit ids. Feel free to make a pull request, I'll check it later on my side.

**Comment by Zverik** [comment]
Fixed in #4.
